### ISSUE TITLE
Meross Cloud plugin support for Meross msg100 (Garagedoor Opener)

### ISSUE THREAD

**Issue by bvz-06** [homebridge-plugins/homebridge-meross-cloud#132]
**Is your feature request related to a problem? Please describe.**

It is not a problem but a request to support another Meross product. The log reports that this (and other) Meross products aren't supported and that a request for supportcan be raised here
29/05/2021, 12:44:09 Starting to advertise 'HOOBS 598C' using bonjour-hap backend!
29/05/2021, 12:44:09 Bridge is running on port 51826.
29/05/2021, 12:44:10 [MerossCloud] Device Type: mss510x, is currently not supported. Submit Feature Requests Here: https://git.io/JtfVC
29/05/2021, 12:44:10 [MerossCloud] Device Type: msg100, is currently not supported. Submit Feature Requests Here: https://git.io/JtfVC
29/05/2021, 12:44:10 [MerossCloud] Device Type: msg100, is currently not supported. Submit Feature Requests Here: https://git.io/JtfVC
29/05/2021, 12:44:10 [MerossCloud] Device Type: mss425f, is currently not supported. Submit Feature Requests Here: https://git.io/JtfVC

**Describe the solution you'd like**

Would like to control the Meross Garagedoor opener (MSG100) with Apple Home using the Hoobs bridge. Also the status (open vs Closed) should be shown 

**Describe alternatives you've considered**

I have been using the Meross V5.0.2 plugin which works, but that requires static ip address on the devices and static message codes and signing keys. Not ideal

**Additional context**

I have beeen able to integrate Meross Garagedoor using IFTTT, but I rather use Apple Homekit and Hoops bridge.

**Comment by JohannesPl** [comment]
Hi. I would also ask for support to that dedicate MSG100 device. What is the current state here?
