### ISSUE TITLE
Please include mss550x support for Meross Cloud pulg-in for homebridge

### ISSUE THREAD

**Issue by djackob-stack** [homebridge-plugins/homebridge-meross-cloud#137]
**Is your feature request related to a problem? Please describe.**
I'm running Meross Cloud, as don't get to set Meross plugin. this is the log i'm seeing after configuring Meross cloud plugin
[MerossCloud] Device Type: mss510x, is currently not supported. Submit Feature Requests Here: https://git.io/JtfVC

**Describe the solution you'd like**

Clear documentation, oriented for hoobs to user either meross or meross cloud plugin for mss550x model

**Describe alternatives you've considered**

**Additional context**

**Comment by bwp91** [comment]
Hi @djackob-stack 

Can look into supporting this with homebridge-meross plugin if this would still interest you.

Thanks
