### ISSUE TITLE
Device type: MSL320cp, currently not supported

### ISSUE THREAD

**Issue by ricm916** [homebridge-plugins/homebridge-meross-cloud#151]
**Is your feature request related to a problem? Please describe.**

Device type: MSL320cp, currently not supported.

**Describe the solution you'd like**

Add support for Device type: MSL320cp.

**Describe alternatives you've considered**

Not alternative found.

**Additional context**

This is the Meross Smart WiFi light strip (https://www.meross.com/product/86/article/). I am currently using homebridge-meross-cloud v1.2.0

**Comment by bwp91** [comment]
Hi @ricm916 

Can look into supporting this with homebridge-meross plugin if this would still interest you.

Thanks
