### ISSUE TITLE
Meross Device Type: msl320m

### ISSUE THREAD

**Issue by accelonace** [homebridge-plugins/homebridge-meross-cloud#154]
New device nor currently supposed. Meross rwb light

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bwp91** [comment]
Hi @accelonace 

Can look into supporting this with homebridge-meross plugin if this would still interest you.

Thanks
